# Generated by GitHub Copilot on 2026-05-08

from __future__ import annotations

from django.db import migrations, models
from django.db.models import Count, Max


def dedupe_responses(apps, schema_editor):
    Response = apps.get_model("review", "Response")

    duplicates = (
        Response.objects.values("school_profile_id", "statement_id")
        .annotate(row_count=Count("id"), keep_id=Max("id"))
        .filter(row_count__gt=1)
    )

    for dup in duplicates:
        (
            Response.objects.filter(
                school_profile_id=dup["school_profile_id"],
                statement_id=dup["statement_id"],
            )
            .exclude(id=dup["keep_id"])
            .delete()
        )


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(dedupe_responses, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="response",
            constraint=models.UniqueConstraint(
                fields=("school_profile", "statement"),
                name="unique_response_per_school_statement",
            ),
        ),
    ]
