# Generated by Django 6.0.5 on 2026-05-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_school_logo_school_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_emblem', models.ImageField(blank=True, null=True, upload_to='branding/')),
            ],
        ),
    ]
