# Generated by GitHub Copilot on 2026-05-08

from __future__ import annotations

from django.db import migrations, models
from django.db.models import Count, Max
import django.db.models.deletion


def copy_school_to_response(apps, schema_editor):
    Response = apps.get_model("review", "Response")
    SchoolProfile = apps.get_model("review", "SchoolProfile")

    profile_to_school = dict(
        SchoolProfile.objects.values_list("id", "school_id")
    )

    for response in Response.objects.all().iterator():
        response.school_id = profile_to_school.get(response.school_profile_id)
        response.save(update_fields=["school"])


def dedupe_school_statement(apps, schema_editor):
    Response = apps.get_model("review", "Response")

    duplicates = (
        Response.objects.values("school_id", "statement_id")
        .annotate(row_count=Count("id"), keep_id=Max("id"))
        .filter(row_count__gt=1)
    )

    for dup in duplicates:
        (
            Response.objects.filter(
                school_id=dup["school_id"],
                statement_id=dup["statement_id"],
            )
            .exclude(id=dup["keep_id"])
            .delete()
        )


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0005_branding"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="school",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="review.school",
            ),
        ),
        migrations.RunPython(copy_school_to_response, migrations.RunPython.noop),
        migrations.RunPython(dedupe_school_statement, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="response",
            name="unique_response_per_school_statement",
        ),
        migrations.RemoveField(
            model_name="response",
            name="school_profile",
        ),
        migrations.AlterField(
            model_name="response",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="review.school",
            ),
        ),
        migrations.AddConstraint(
            model_name="response",
            constraint=models.UniqueConstraint(
                fields=("school", "statement"),
                name="unique_response_per_school_statement",
            ),
        ),
    ]
