# Generated by GitHub Copilot on 2026-05-08

from __future__ import annotations

import django.core.validators
from django.db import migrations, models
from django.db.models import F, Value


def remap_ratings_0_4_to_1_5(apps, schema_editor):
    """Remap legacy 0–4 scale to OXLIP 1–5 scale.

    Assumption based on prior UI: 0 was worst and 4 was best.
    New scale is reversed and 1 is best, 5 is worst.

    Mapping: new = 5 - old
      0 -> 5
      1 -> 4
      2 -> 3
      3 -> 2
      4 -> 1
    """

    Response = apps.get_model("review", "Response")

    Response.objects.exclude(rating__isnull=True).update(rating=Value(5) - F("rating"))


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0006_response_to_school"),
    ]

    operations = [
        migrations.RunPython(remap_ratings_0_4_to_1_5, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="response",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
