# Generated by GitHub Copilot on 2026-05-08

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def assign_default_period(apps, schema_editor):
    ReviewPeriod = apps.get_model("review", "ReviewPeriod")
    Response = apps.get_model("review", "Response")

    period, _ = ReviewPeriod.objects.get_or_create(
        year=timezone.now().year,
        round=1,
    )

    Response.objects.filter(period__isnull=True).update(period_id=period.id)


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0007_rating_scale_oxlip"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveSmallIntegerField(default=timezone.now().year)),
                ("round", models.PositiveSmallIntegerField(choices=[(1, "Round 1"), (2, "Round 2"), (3, "Round 3")], default=1)),
            ],
            options={
                "ordering": ("-year", "round"),
            },
        ),
        migrations.AddConstraint(
            model_name="reviewperiod",
            constraint=models.UniqueConstraint(fields=("year", "round"), name="unique_review_period_year_round"),
        ),
        migrations.AddField(
            model_name="response",
            name="period",
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to="review.reviewperiod"),
        ),
        migrations.RunPython(assign_default_period, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="response",
            name="unique_response_per_school_statement",
        ),
        migrations.AlterField(
            model_name="response",
            name="period",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="review.reviewperiod"),
        ),
        migrations.AddConstraint(
            model_name="response",
            constraint=models.UniqueConstraint(fields=("school", "period", "statement"), name="unique_response_per_school_statement"),
        ),
    ]
