# Generated by Django 6.0.5 on 2026-05-08 13:44

from django.db import migrations, models


def backfill_schoolprofile_schools(apps, schema_editor):
    SchoolProfile = apps.get_model("review", "SchoolProfile")
    through = SchoolProfile.schools.through

    rows = []
    for profile_id, school_id in SchoolProfile.objects.values_list("id", "school_id"):
        if not school_id:
            continue
        rows.append(through(schoolprofile_id=profile_id, school_id=school_id))

    # Ignore conflicts if someone already added entries.
    through.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_evaluation_created_at_evaluation_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='school_profiles', to='review.school'),
        ),
        migrations.RunPython(backfill_schoolprofile_schools, migrations.RunPython.noop),
    ]
