# Generated by Django 6.0.5 on 2026-05-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0013_category_is_active"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Response",
        ),
        migrations.DeleteModel(
            name="Statement",
        ),
    ]
