# Generated by Django 6.0.5 on 2026-05-11 08:02

import django.db.models.deletion
import review.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_remove_statement_and_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InDepthArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='InDepthReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=review.models.current_academic_year_start)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.indeptharea')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_indepth_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-year', 'school__name', 'area__order', 'area__name'),
            },
        ),
        migrations.CreateModel(
            name='InDepthStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.indeptharea')),
            ],
            options={
                'ordering': ('area__order', 'area__name', 'statement_number'),
            },
        ),
        migrations.CreateModel(
            name='InDepthResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies', models.BooleanField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.indepthreview')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.indepthstatement')),
            ],
            options={
                'ordering': ('statement__area__order', 'statement__area__name', 'statement__statement_number'),
            },
        ),
        migrations.AddConstraint(
            model_name='indepthreview',
            constraint=models.UniqueConstraint(fields=('school', 'year', 'area'), name='unique_indepth_review_per_school_year_area'),
        ),
        migrations.AddConstraint(
            model_name='indepthstatement',
            constraint=models.UniqueConstraint(fields=('area', 'statement_number'), name='unique_indepth_statement_per_area_number'),
        ),
        migrations.AddConstraint(
            model_name='indepthresponse',
            constraint=models.UniqueConstraint(fields=('review', 'statement'), name='unique_indepth_response_per_review_statement'),
        ),
    ]
