# Generated by Django 6.0.5 on 2026-05-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0015_indeptharea_indepthreview_indepthstatement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indeptharea',
            name='needs_attention_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='indeptharea',
            name='strong_standard_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='indepthresponse',
            name='next_steps',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='indepthreview',
            name='secondary_applies',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indepthreview',
            name='secondary_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='indepthreview',
            name='step',
            field=models.CharField(choices=[('expected', 'Expected Standard'), ('secondary', 'Secondary Standard'), ('justification', 'Justification')], default='expected', max_length=20),
        ),
    ]
