# Generated by Django 6.0.5 on 2026-05-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_indeptharea_needs_attention_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indepthstatement',
            options={'ordering': ('area__order', 'area__name', 'standard_type', 'statement_number')},
        ),
        migrations.RemoveConstraint(
            model_name='indepthstatement',
            name='unique_indepth_statement_per_area_number',
        ),
        migrations.AddField(
            model_name='indepthreview',
            name='justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='indepthstatement',
            name='standard_type',
            field=models.CharField(choices=[('expected', 'Expected Standard'), ('needs_attention', 'Needs Attention'), ('strong_standard', 'Strong Standard')], default='expected', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='indepthstatement',
            constraint=models.UniqueConstraint(fields=('area', 'standard_type', 'statement_number'), name='unique_indepth_statement_per_area_type_number'),
        ),
    ]
