# Generated by Django 6.0.5 on 2026-05-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0017_indepth_statement_standard_type_review_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='indeptharea',
            name='is_safeguarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indepthresponse',
            name='rag',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='indepthreview',
            name='step',
            field=models.CharField(choices=[('expected', 'Expected Standard'), ('urgent_improvement', 'Urgent Improvement'), ('strong_standard', 'Strong Standard'), ('exceptional', 'Exceptional'), ('justification', 'Justification'), ('secondary', 'Secondary Standard')], default='expected', max_length=20),
        ),
        migrations.AlterField(
            model_name='indepthstatement',
            name='standard_type',
            field=models.CharField(choices=[('expected', 'Expected Standard'), ('urgent_improvement', 'Urgent Improvement'), ('needs_attention', 'Needs Attention'), ('strong_standard', 'Strong Standard'), ('exceptional', 'Exceptional')], default='expected', max_length=20),
        ),
    ]
