# Generated by Django 6.0.5 on 2026-05-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0018_indeptharea_safeguarding_indepthresponse_rag_new_standard_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='indepthreview',
            name='qa_reflection',
            field=models.TextField(blank=True, default=''),
        ),
    ]
