# Generated by Django 6.0.5 on 2026-06-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0021_remove_legacy_indepth_areas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indepthresponse',
            options={'ordering': ('subsection__area__order', 'subsection__order')},
        ),
    ]
