# Generated by Django 6.0.5 on 2026-06-13 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0025_indepthstandard_indepthjudgementarea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indepthresponse',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='indepthresponse',
            name='judgement_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='review.indepthjudgementarea'),
        ),
        migrations.AddField(
            model_name='indepthresponse',
            name='rag',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green')], default='', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='indepthresponse',
            constraint=models.UniqueConstraint(fields=('review', 'judgement_area'), name='unique_indepth_response_per_review_judgement_area'),
        ),
    ]
