# Generated by Django 6.0.5 on 2026-07-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0028_evaluation_overridden_at_evaluation_overridden_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indepthreview',
            name='needs_attention_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
