# Generated by Django 6.0.5 on 2026-08-23 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0029_indepthreview_needs_attention_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalate_bands', models.JSONField(blank=True, default=list)),
                ('escalate_persisting_amber', models.BooleanField(default=False, help_text='Also escalate a risk that has stayed at Amber across terms. Off by agreement — the starting rule is Red only.')),
            ],
            options={
                'verbose_name': 'Risk settings',
                'verbose_name_plural': 'Risk settings',
            },
        ),
        migrations.AlterField(
            model_name='reviewperiod',
            name='round',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Autumn'), (2, 'Spring'), (3, 'Summer')], default=1),
        ),
        migrations.CreateModel(
            name='TrustCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('evaluation_area', 'OSED evaluation area'), ('operations_domain', 'Operations & Resources domain')], max_length=20)),
                ('domain_key', models.SlugField(blank=True, default='')),
                ('domain_name', models.CharField(blank=True, default='', max_length=100)),
                ('routes_to', models.CharField(choices=[('SIV', 'SIV'), ('TFORS', 'TFORS')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('indepth_area', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trust_category', to='review.indeptharea')),
            ],
            options={
                'verbose_name': 'Trust category',
                'verbose_name_plural': 'Trust categories',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mitigation', models.TextField(blank=True, default='')),
                ('owner', models.CharField(blank=True, default='', max_length=100)),
                ('review_point', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.TextField(blank=True, default='')),
                ('close_qa_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('close_qa_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_closed_risks', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_risks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_risks', to=settings.AUTH_USER_MODEL)),
                ('opened_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_opened', to='review.reviewperiod')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='review.school')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='review.trustcategory')),
            ],
            options={
                'ordering': ('status', '-created_at'),
                'permissions': [('qa_risk', 'Can QA risk register entries')],
            },
        ),
        migrations.CreateModel(
            name='RiskRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('likelihood', models.CharField(choices=[('Unlikely', 'Unlikely'), ('Possible', 'Possible'), ('Highly probable', 'Highly probable')], max_length=20)),
                ('band', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high_priority', 'High priority'), ('medium_priority', 'Medium priority'), ('monitor', 'Monitor'), ('low_risk', 'Low risk')], default='', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('qa_at', models.DateTimeField(blank=True, null=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_ratings', to='review.reviewperiod')),
                ('qa_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_risk_ratings', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_risk_ratings', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='review.risk')),
            ],
            options={
                'ordering': ('-period__year', '-period__round'),
                'constraints': [models.UniqueConstraint(fields=('risk', 'period'), name='unique_risk_rating_per_period')],
            },
        ),
    ]
