# Generated by Django 6.0.5 on 2026-08-23 18:27

import django.db.models.deletion
import review.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0030_risksettings_alter_reviewperiod_round_trustcategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='school',
            name='is_mainstream',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='OperationsMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('benchmark_source', models.TextField(blank=True, default='')),
                ('rule', models.CharField(choices=[('band_choice', 'Choose the band statement that applies'), ('numeric_range', 'Numeric value against banded ranges'), ('vs_comparator_pct', 'Numeric value against a national comparator (% tolerance)'), ('vs_comparator_points', 'Numeric value against a national comparator (percentage points)'), ('count_threshold', 'Count met against thresholds'), ('statutory_dates', 'Computed from statutory compliance due dates'), ('complaints_trend', "Computed from the school's own complaints trend"), ('grant_publication', 'Computed from the applicable grant checklist')], max_length=30)),
                ('evidence', models.CharField(choices=[('benchmarked', 'Hard-benchmarked'), ('judgement', 'Judgement-based')], default='judgement', max_length=20)),
                ('cycle', models.CharField(choices=[('termly', 'Termly'), ('annual', 'Annual')], default='termly', max_length=10)),
                ('value_label', models.CharField(blank=True, default='', max_length=100)),
                ('help_text', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('domain', models.ForeignKey(limit_choices_to={'group': 'operations_domain'}, on_delete=django.db.models.deletion.PROTECT, related_name='operations_metrics', to='review.trustcategory')),
            ],
            options={
                'verbose_name': 'Operations metric',
                'ordering': ('domain__order', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='GrantPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=review.models.current_academic_year_start)),
                ('grant', models.CharField(choices=[('pupil_premium', 'Pupil Premium'), ('inclusive_mainstream', 'Inclusive Mainstream Fund'), ('pe_sport', 'PE and Sport Premium')], max_length=30)),
                ('status', models.CharField(choices=[('published', 'Published and on file, on time'), ('drafted', 'Drafted but not published'), ('missed', 'Deadline missed')], max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_publications', to='review.school')),
            ],
            options={
                'ordering': ('school__name', '-year', 'grant'),
                'constraints': [models.UniqueConstraint(fields=('school', 'year', 'grant'), name='unique_grant_publication_per_school_year')],
            },
        ),
        migrations.CreateModel(
            name='OperationsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('band_choice', models.CharField(blank=True, choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red'), ('blue', 'Blue')], default='', max_length=10)),
                ('commentary', models.TextField(blank=True, default='')),
                ('manual_red_reason', models.TextField(blank=True, default='')),
                ('rag', models.CharField(blank=True, choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red'), ('blue', 'Blue')], default='', max_length=10)),
                ('source', models.CharField(choices=[('manual', 'Entered by hand'), ('import', 'Imported from a feed')], default='manual', max_length=10)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_entries', to='review.reviewperiod')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_entries', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_entries', to='review.school')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='review.complainttheme')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='review.operationsmetric')),
            ],
            options={
                'verbose_name_plural': 'Operations entries',
                'ordering': ('-period__year', '-period__round', 'metric__order'),
                'constraints': [models.UniqueConstraint(fields=('school', 'period', 'metric'), name='unique_operations_entry')],
            },
        ),
        migrations.CreateModel(
            name='OperationsMetricBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(blank=True, choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], default='', max_length=20)),
                ('green_descriptor', models.TextField(blank=True, default='')),
                ('amber_descriptor', models.TextField(blank=True, default='')),
                ('red_descriptor', models.TextField(blank=True, default='')),
                ('green_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('green_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('amber_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('amber_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('amber_tolerance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('comparator_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('comparator_year', models.CharField(blank=True, default='', max_length=20)),
                ('comparator_source', models.CharField(blank=True, default='', max_length=200)),
                ('step_change', models.PositiveSmallIntegerField(default=3)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='review.operationsmetric')),
            ],
            options={
                'ordering': ('metric__order', 'phase'),
                'constraints': [models.UniqueConstraint(fields=('metric', 'phase'), name='unique_operations_band_per_metric_phase')],
            },
        ),
        migrations.CreateModel(
            name='OperationsMetricVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=review.models.current_academic_year_start)),
                ('is_visible', models.BooleanField(default=False)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibility', to='review.operationsmetric')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_visibility', to='review.school')),
            ],
            options={
                'verbose_name_plural': 'Operations metric visibility',
                'ordering': ('school__name', '-year', 'metric__order'),
                'constraints': [models.UniqueConstraint(fields=('school', 'year', 'metric'), name='unique_operations_visibility')],
            },
        ),
        migrations.CreateModel(
            name='OperationsNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_notes', to='review.reviewperiod')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_notes', to='review.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-period__year', '-period__round'),
                'constraints': [models.UniqueConstraint(fields=('school', 'period'), name='unique_operations_note_per_term')],
            },
        ),
        migrations.CreateModel(
            name='StatutoryComplianceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('fire_risk_assessment', 'Fire risk assessment'), ('legionella', 'Legionella'), ('asbestos', 'Asbestos'), ('gas_electrical', 'Gas / electrical safety'), ('epc', 'EPC')], max_length=30)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('action_plan_in_place', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_items', to='review.school')),
            ],
            options={
                'ordering': ('school__name', 'item'),
                'constraints': [models.UniqueConstraint(fields=('school', 'item'), name='unique_statutory_item_per_school')],
            },
        ),
    ]
