# Generated by Django 6.0.5 on 2026-08-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0031_complainttheme_school_is_mainstream_operationsmetric_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
