# Generated by Django 6.0.5 on 2026-08-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0032_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branding',
            options={'verbose_name': 'Branding', 'verbose_name_plural': 'Branding'},
        ),
        migrations.AlterModelOptions(
            name='indeptharea',
            options={'ordering': ('order', 'name'), 'verbose_name': 'In-depth area', 'verbose_name_plural': 'In-depth areas'},
        ),
        migrations.AlterModelOptions(
            name='indepthjudgementarea',
            options={'ordering': ('standard', 'order'), 'verbose_name': 'In-depth judgement area', 'verbose_name_plural': 'In-depth judgement areas'},
        ),
        migrations.AlterModelOptions(
            name='indepthresponse',
            options={'ordering': ('id',), 'verbose_name': 'In-depth response', 'verbose_name_plural': 'In-depth responses'},
        ),
        migrations.AlterModelOptions(
            name='indepthreview',
            options={'ordering': ('-year', 'school__name', 'area__order', 'area__name'), 'verbose_name': 'In-depth review', 'verbose_name_plural': 'In-depth reviews'},
        ),
        migrations.AlterModelOptions(
            name='indepthstandard',
            options={'ordering': ('area__order', 'order'), 'verbose_name': 'In-depth standard', 'verbose_name_plural': 'In-depth standards'},
        ),
        migrations.AlterModelOptions(
            name='indepthsubsection',
            options={'ordering': ('area__order', 'area__name', 'order'), 'verbose_name': 'In-depth sub-section', 'verbose_name_plural': 'In-depth sub-sections'},
        ),
    ]
