# Generated by Django 6.0.5 on 2026-09-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0034_historicalevaluation_historicalindepthresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='role',
            field=models.CharField(choices=[('FULL', 'Full access'), ('GOVERNOR', 'Governor (read-only, limited pages)')], default='FULL', help_text='Governors see only the School Dashboard, Trust Dashboard and Evaluation pages, read-only, for their own school(s).', max_length=20),
        ),
    ]
