# Generated by Django 6.0.5 on 2026-09-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0035_schoolprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='powerbi_school_name',
            field=models.CharField(blank=True, default='', help_text="The exact value this school appears as in the Power BI report's School slicer. Leave blank to show no report for this school.", max_length=200, verbose_name='Power BI school name'),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(condition=models.Q(('powerbi_school_name', ''), _negated=True), fields=('powerbi_school_name',), name='unique_powerbi_school_name', violation_error_message='Another school is already using that Power BI school name.'),
        ),
    ]
