"""
Django settings for osed project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load a local .env file (for local development only). On Azure the real
# environment variables are set by the platform, so the .env file is absent there
# and this is a no-op. The import is optional so settings never crash if
# python-dotenv isn't installed.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / ".env")
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in ("1", "true", "yes", "on")


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-+0x_uu4=piy$m$gkpzn5t$4^qogyi-z$a64xbyl!@u&nm#1b6&",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False so production is safe even if DEBUG is never set.
# For local development, set DEBUG=1 in your .env file.
DEBUG = _env_bool("DEBUG", default=False)

if not DEBUG and not os.getenv("SECRET_KEY"):
    raise ImproperlyConfigured(
        "SECRET_KEY is required when DEBUG=0 (production). "
        "Set the SECRET_KEY environment variable."
    )

_raw_allowed_hosts = os.getenv("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in _raw_allowed_hosts.split(",") if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# Azure App Service exposes the public hostname via WEBSITE_HOSTNAME. Custom
# domains (e.g. osed.oxlip.uk) aren't covered by this and must be added via
# the ALLOWED_HOSTS env var instead.
_azure_hostname = os.getenv("WEBSITE_HOSTNAME", "").strip()
if _azure_hostname and _azure_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_azure_hostname)

# Azure's platform warm-up/liveness probes reach the container internally,
# not via the public hostname, so Django rejects them with DisallowedHost.
# They arrive with two kinds of Host header:
#   * the container's own private link-local IP (e.g. 169.254.129.4:8000) —
#     the IP changes per container, so it must be discovered at runtime, and
#   * a loopback name (e.g. localhost:8080).
# Trust both so the probes pass. Gated on Azure (WEBSITE_HOSTNAME) so local
# behaviour is unchanged. These are all host values that only something
# already inside the container's network can present, so this does not widen
# the set of externally reachable hosts or weaken the security model.
if _azure_hostname:
    import socket

    try:
        _container_ips = {
            info[4][0] for info in socket.getaddrinfo(socket.gethostname(), None)
        }
    except OSError:
        _container_ips = set()
    _internal_probe_hosts = _container_ips | {"localhost", "127.0.0.1"}
    ALLOWED_HOSTS.extend(h for h in _internal_probe_hosts if h not in ALLOWED_HOSTS)

# Trust every configured host as an HTTPS CSRF origin, so a custom domain
# only needs to be added in one place (the ALLOWED_HOSTS env var).
CSRF_TRUSTED_ORIGINS = list({
    f"https://{host}" for host in ALLOWED_HOSTS if host not in ("localhost", "127.0.0.1")
})


# Application definition

INSTALLED_APPS = [
    'django.contrib.sites',
    # Replaces 'django.contrib.admin' so admin.site is OsedAdminSite, which
    # groups the review app's models into named sections on the index.
    'review.admin_site.OsedAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # WhiteNoise: must come before staticfiles so its dev static handler is used.
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.microsoft',

    # Row-level version history on the models holding typed commentary. Provides
    # the admin History tab and Model.history.as_of(<datetime>).
    'simple_history',

    'review',
]


USE_AZURE_MEDIA_STORAGE = os.getenv("USE_AZURE_MEDIA_STORAGE", "").lower() in ("1", "true", "yes")
if USE_AZURE_MEDIA_STORAGE:
    INSTALLED_APPS.append("storages")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    # Must sit after AuthenticationMiddleware: it reads request.user to stamp
    # history_user. Changes made by a management command or the shell record no
    # user, which is correct -- there was no request.
    'simple_history.middleware.HistoryRequestMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'osed.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'review.context_processors.branding',
                'review.context_processors.nav_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'osed.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
if DATABASE_URL:
    DATABASES["default"] = dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        ssl_require=not DEBUG,
    )
elif not DEBUG:
    # In production, falling back to SQLite means data resets on each deploy.
    raise ImproperlyConfigured(
        "DATABASE_URL is required when DEBUG=0 (production). "
        "Set DATABASE_URL to your Azure Postgres connection string."
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Storage backends (Django >= 4.2)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Whitenoise static file serving
if not DEBUG:
    STORAGES["staticfiles"]["BACKEND"] = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Respect the platform's proxy headers for https detection
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Production HTTPS/cookie hardening. Only applied when DEBUG is off so local
# development over plain HTTP is unaffected.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


SITE_ID = 1

# Auth: use Microsoft SSO for sign-in, while we keep authorization in-app.
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

ACCOUNT_LOGIN_METHODS = {'email'}
# password1 must be listed: allauth only builds a password field on its login
# form when the site's signup fields include one. The login page offers the
# email/password form beside the Microsoft button (reinstated Sept 2026 for staff
# who cannot use Microsoft SSO); /accounts/login/ is rate-limited by allauth,
# /admin/login/ is not.
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
# Access is by Microsoft SSO or password, plus pre-provisioning. allauth has no setting that
# closes /accounts/signup/ — the adapter's is_open_for_signup hook is the only
# switch, and its pre_login hook applies the same provisioning rule to password
# logins that the social adapter applies to Microsoft ones.
ACCOUNT_ADAPTER = 'review.allauth_adapters.OsedAccountAdapter'

# Skip allauth's unstyled "Sign out?" confirmation page — log out straight away
# on GET. Trade-off: allows logout-CSRF (a third party could sign a user out via
# a crafted link); harmless here (no data exposure, just re-login).
ACCOUNT_LOGOUT_ON_GET = True

SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = False
SOCIALACCOUNT_ADAPTER = 'review.allauth_adapters.RestrictMicrosoftLoginAdapter'
# Skip allauth's unstyled "Continue with Microsoft" intermediate page — the login
# link redirects straight to Microsoft on GET. Safe with a single SSO provider.
SOCIALACCOUNT_LOGIN_ON_GET = True

MICROSOFT_CLIENT_ID = os.getenv('MICROSOFT_CLIENT_ID', '')
MICROSOFT_CLIENT_SECRET = os.getenv('MICROSOFT_CLIENT_SECRET', '')
# Use "organizations" for Entra org accounts, or a tenant ID to lock to one tenant.
MICROSOFT_TENANT = os.getenv('MICROSOFT_TENANT', 'organizations')


# --- Power BI Context Dashboard -------------------------------------------
# The supplied embed is a user-owns-data "secure embed" (`autoAuth=true`): the
# viewer signs in to Power BI with their own Microsoft account, and OSED chooses
# only which school the report opens at. There is no secret here and no
# service-to-service call -- deliberately a separate concern from
# MICROSOFT_CLIENT_ID above, which is the delegated SSO app. The `ctid` inside
# the embed URL is the report's tenant and is NOT the same question as
# MICROSOFT_TENANT; do not try to reconcile them.
#
# No ImproperlyConfigured guard on purpose. Absent or wrong config must degrade
# to an explanatory panel on one page, not refuse to boot the site.
POWERBI_ENABLED = _env_bool("POWERBI_ENABLED", default=False)
# The full embed string as supplied by the report author, pasted verbatim.
# Stored whole rather than split into report id + tenant id and reassembled:
# reassembling a vendor-supplied URL is a way to get it wrong.
POWERBI_REPORT_URL = os.getenv("POWERBI_REPORT_URL", "").strip()
# The report's own `Table/Column` holding the school name, e.g. "Schools/School".
# Neither part may contain a space -- a Power BI URL filter cannot address one.
# Blank or unusable means the page shows "not set up yet" rather than an
# unfiltered report.
POWERBI_FILTER_TARGET = os.getenv("POWERBI_FILTER_TARGET", "").strip()
POWERBI_REPORT_TITLE = os.getenv("POWERBI_REPORT_TITLE", "Oxlip Context Dashboard").strip()


SOCIALACCOUNT_PROVIDERS = {
    'microsoft': {
        'APPS': [
            {
                'client_id': MICROSOFT_CLIENT_ID,
                'secret': MICROSOFT_CLIENT_SECRET,
                'settings': {
                    'tenant': MICROSOFT_TENANT,
                },
            }
        ]
    }
}


LOGIN_REDIRECT_URL = "/review/dashboard/"
LOGIN_URL = "/accounts/login/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Logging — always emit Django errors to stderr so they appear in the platform logs
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        # The root is WARNING, which would swallow the Context Dashboard's
        # access record -- who opened the report page, for which school. That is
        # the only read-trail OSED can produce for this feature (Power BI logs
        # the viewer's own identity, in a different system), so it is raised
        # here rather than mislabelled as a WARNING to get past the root level.
        "review": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Demo convenience: allow serving local media without enabling DEBUG.
# (Not recommended for real production; prefer cloud storage like Azure/S3.)
SERVE_MEDIA = _env_bool("SERVE_MEDIA", default=False)

# If you are using committed demo media assets (e.g. seeded logos/branding) and
# want them served by WhiteNoise, enable MEDIA_AS_STATIC=1.
# This makes ImageField URLs resolve under STATIC_URL (e.g. /static/media/...).
MEDIA_AS_STATIC = _env_bool("MEDIA_AS_STATIC", default=False)
if MEDIA_AS_STATIC and not USE_AZURE_MEDIA_STORAGE:
    MEDIA_URL = f"{STATIC_URL}media/"
    SERVE_MEDIA = False

if USE_AZURE_MEDIA_STORAGE:
    AZURE_ACCOUNT_NAME = os.getenv("AZURE_ACCOUNT_NAME", "").strip()
    AZURE_ACCOUNT_KEY = os.getenv("AZURE_ACCOUNT_KEY", "").strip()
    AZURE_CONTAINER = os.getenv("AZURE_CONTAINER", "media").strip() or "media"
    AZURE_CUSTOM_DOMAIN = os.getenv("AZURE_CUSTOM_DOMAIN", "").strip()

    if not AZURE_ACCOUNT_NAME or not AZURE_ACCOUNT_KEY:
        raise ImproperlyConfigured(
            "USE_AZURE_MEDIA_STORAGE is enabled but AZURE_ACCOUNT_NAME/AZURE_ACCOUNT_KEY are missing."
        )

    STORAGES["default"]["BACKEND"] = "storages.backends.azure_storage.AzureStorage"

    # Optional convenience: make MEDIA_URL reflect the blob endpoint.
    # FileField/ImageField URLs are generated via storage.url(...) either way.
    if AZURE_CUSTOM_DOMAIN:
        MEDIA_URL = f"https://{AZURE_CUSTOM_DOMAIN.rstrip('/')}/"
    else:
        MEDIA_URL = f"https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_CONTAINER}/"
